#line 2 "inferencerule_parser.yy.c"

#line 4 "inferencerule_parser.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer inferencerule_parser_create_buffer
#define yy_delete_buffer inferencerule_parser_delete_buffer
#define yy_flex_debug inferencerule_parser_flex_debug
#define yy_init_buffer inferencerule_parser_init_buffer
#define yy_flush_buffer inferencerule_parser_flush_buffer
#define yy_load_buffer_state inferencerule_parser_load_buffer_state
#define yy_switch_to_buffer inferencerule_parser_switch_to_buffer
#define yyin inferencerule_parserin
#define yyleng inferencerule_parserleng
#define yylex inferencerule_parserlex
#define yylineno inferencerule_parserlineno
#define yyout inferencerule_parserout
#define yyrestart inferencerule_parserrestart
#define yytext inferencerule_parsertext
#define yywrap inferencerule_parserwrap
#define yyalloc inferencerule_parseralloc
#define yyrealloc inferencerule_parserrealloc
#define yyfree inferencerule_parserfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE inferencerule_parserrestart(inferencerule_parserin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int inferencerule_parserleng;

extern FILE *inferencerule_parserin, *inferencerule_parserout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up inferencerule_parsertext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up inferencerule_parsertext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via inferencerule_parserrestart()), so that the user can continue scanning by
	 * just pointing inferencerule_parserin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when inferencerule_parsertext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int inferencerule_parserleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow inferencerule_parserwrap()'s to do buffer switches
 * instead of setting up a fresh inferencerule_parserin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void inferencerule_parserrestart (FILE *input_file  );
void inferencerule_parser_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE inferencerule_parser_create_buffer (FILE *file,int size  );
void inferencerule_parser_delete_buffer (YY_BUFFER_STATE b  );
void inferencerule_parser_flush_buffer (YY_BUFFER_STATE b  );
void inferencerule_parserpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void inferencerule_parserpop_buffer_state (void );

static void inferencerule_parserensure_buffer_stack (void );
static void inferencerule_parser_load_buffer_state (void );
static void inferencerule_parser_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER inferencerule_parser_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE inferencerule_parser_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE inferencerule_parser_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE inferencerule_parser_scan_bytes (yyconst char *bytes,int len  );

void *inferencerule_parseralloc (yy_size_t  );
void *inferencerule_parserrealloc (void *,yy_size_t  );
void inferencerule_parserfree (void *  );

#define yy_new_buffer inferencerule_parser_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        inferencerule_parserensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            inferencerule_parser_create_buffer(inferencerule_parserin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        inferencerule_parserensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            inferencerule_parser_create_buffer(inferencerule_parserin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *inferencerule_parserin = (FILE *) 0, *inferencerule_parserout = (FILE *) 0;

typedef int yy_state_type;

extern int inferencerule_parserlineno;

int inferencerule_parserlineno = 1;

extern char *inferencerule_parsertext;
#define yytext_ptr inferencerule_parsertext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up inferencerule_parsertext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	inferencerule_parserleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[354] =
    {   0,
        0,    0,   36,   35,    9,   35,   22,   35,   35,   24,
       25,   23,   35,    8,   26,   35,   35,   35,   35,    6,
        7,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   31,
       32,    9,    0,   33,    0,   34,   34,   34,   34,   34,
       34,   34,    0,    0,    0,    1,    8,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    3,    0,    0,    3,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,    0,    0,    0,    0,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   20,   18,
       19,    1,   17,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       34,   34,   34,   34,   34,   34,   29,   34,   34,   34,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,   30,   34,   34,   34,
       34,   34,   34,   34,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   15,   34,   34,   34,
       34,   34,   13,   27,   34,   21,    0,    0,    0,    0,
        3,    0,    0,    0,    0,    0,    0,    0,    0,   34,
       34,   34,   34,   34,   34,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   14,    5,    4,   34,   34,   34,
       34,   28,    0,    0,    0,    0,    0,    0,    0,   10,
       11,   12,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    7,    1,    1,    8,
        9,   10,    1,   11,    1,    1,   12,   13,   14,   15,
       16,   13,   13,   13,   13,   13,   13,   17,   18,    1,
        1,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   24,   26,   24,   24,   27,   24,   28,   29,   24,
       24,   30,   31,   32,   33,   34,   24,   24,   24,   24,
       35,   36,   37,    1,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   24,   24,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,    1,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[358] =
    {   0,
        0,    0,  694,  695,   63,   63,  695,   27,   32,  695,
      695,  695,   63,   69,  695,  664,  669,  665,  662,  695,
      695,   38,  642,   38,   43,   27,   48,  632,   55,   44,
      644,   42,  635,   60,   62,   54,  635,  637,  640,  695,
      695,  110,   93,  695,  679,  107,  111,  117,  121,  125,
      129,  133,  639,   63,  670,    0,  138,  650,  659,  652,
      645,  633,  613,  618,  616,  616,  105,  626,   59,  624,
      616,  695,  624,  626,  621,  619,  621,  614,  616,  617,
      616,  603,   76,  612,  608,  610,  614,  606,  600,  596,
      602,  103,  145,  152,  175,  179,  183,  187,  195,  199,

      206,  211,  607,  588,  597,  636,  164,    0,  618,  617,
      615,  616,  598,  593,  178,  126,  598,  588,  598,  593,
      588,  591,  590,  576,  196,  575,  587,  586,  570,  584,
      194,  578,  579,  581,  573,  579,  574,  578,  568,  235,
      246,  250,  255,  259,  263,  267,  271,  288,  579,  695,
      695,  695,  695,  594,  591,  573,  569,  563,  569,  557,
      127,  571,  553,  551,  554,  564,  564,  556,  548,  552,
      548,  549,  545,  551,  555,  536,  552,  552,  543,  541,
      537,  133,  543,  533,  547,  544,  532,  540,  541,  540,
      294,  302,  310,  315,  319,  326,  330,  335,  339,  343,

      534,  559,  552,  534,  528,  535,  531,  524,  520,  517,
      521,  523,  527,  518,  510,  521,  524,  509,  512,  518,
      506,  511,  515,  517,  504,  506,  502,  514,  499,  497,
      144,  509,  501,  497,  489,  695,  353,  362,  368,  372,
      376,  381,  387,  393,  500,  509,  523,  502,  492,  489,
      492,  485,  490,  500,  491,  489,  493,  485,  478,  490,
      478,  485,  474,  485,  484,  462,  695,  398,  409,  413,
      420,  425,  695,  695,  429,  695,  214,  494,  476,  432,
      416,  425,  418,  421,  402,  414,  410,  388,  370,  433,
      442,  456,  437,  465,  469,  393,  390,  378,  349,  343,

      333,  314,  314,  318,  473,  695,  695,  482,  487,  492,
      497,  477,  329,  328,  269,  291,  289,  293,  271,  695,
      695,  695,  695,  288,  297,  293,  285,  269,  248,  276,
      271,  260,  258,  234,  224,  236,  233,  221,  230,  191,
      200,  201,  207,  191,  177,  184,  157,  143,  138,  133,
       87,   70,  695,  519,   69,  522,  525
    } ;

static yyconst flex_int16_t yy_def[358] =
    {   0,
      353,    1,  353,  353,  353,  354,  353,  355,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  354,  353,  354,  355,  355,  355,  355,  355,
      355,  355,  353,  353,  356,  357,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  353,  353,  353,  356,  356,  357,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  355,  355,  355,  355,
      355,  355,  355,  355,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  355,  355,  355,
      355,  355,  353,  353,  355,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  355,
      355,  355,  355,  355,  355,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  355,  353,  353,  353,  353,  353,
      355,  355,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,    0,  353,  353,  353,  353
    } ;

static yyconst flex_int16_t yy_nxt[760] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,    4,
       12,   13,   14,   14,   14,   14,    4,   15,    4,   16,
        4,    4,    4,    4,    4,    4,    4,    4,    4,   17,
       18,    4,   19,    4,   20,    4,   21,    4,   22,   23,
       24,   25,   26,    4,   27,    4,   28,   29,   30,   31,
       32,   33,    4,   34,   35,   36,   37,    4,   38,    4,
        4,   39,   40,   41,   42,   42,   44,   47,   70,   48,
       53,   46,   55,   49,   56,   50,   66,   51,   52,   62,
       54,   57,   57,   57,   57,   68,   71,   63,   67,   69,
       72,   80,   64,   74,   77,   81,   44,   75,   45,  153,

       78,  104,   83,   72,   85,   76,   84,   88,   86,  105,
       72,   42,   42,  120,   89,  352,  121,  131,   87,   93,
       93,   93,   93,   93,   93,   93,   93,  132,   45,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   94,
       57,   57,   57,   57,  117,   72,  139,   93,   93,   93,
       93,  118,  153,   97,   93,   93,   93,   93,   72,  351,
       96,   98,  153,  107,   95,  152,  208,  209,   99,  350,
      100,   72,  226,  227,  101,   72,  102,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,

       93,   93,   93,  263,  349,  348,  140,   93,   93,   93,
       93,   93,   93,   93,   93,  347,  158,  141,   93,   93,
       93,   93,  142,   93,   93,   93,   93,  159,  160,  346,
      153,  345,  179,  296,  170,  145,  144,  161,  171,  297,
       72,  146,  143,  180,  181,  172,  173,   93,   93,   93,
       93,  147,  344,  182,  343,  342,  341,  148,   93,   93,
       93,   93,   93,   93,   93,   93,   72,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,  340,  326,  339,
      191,  338,  193,  195,  327,  337,  194,  196,  336,  192,

       93,   93,   93,   93,  335,  197,   93,   93,   93,   93,
      236,  334,  333,  199,   93,   93,   93,   93,  332,  331,
      198,  330,   93,   93,   93,   93,   72,   93,   93,   93,
       93,   93,   93,   93,   93,   72,  329,  200,   93,   93,
       93,   93,   93,   93,   93,   93,  328,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,  325,
      324,  319,  237,  238,  239,   93,   93,   93,   93,   72,
      318,  317,  240,  242,   93,   93,   93,   93,  267,  241,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,  243,   93,   93,   93,   93,   72,  244,   93,

       93,   93,   93,  273,  316,   93,   93,   93,   93,  274,
       93,   93,   93,   93,  268,  315,  269,  314,  313,   72,
      270,   93,   93,   93,   93,   93,   93,   93,   93,   72,
      271,  275,   93,   93,   93,   93,  272,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
      308,  309,  310,  290,   93,   93,   93,   93,  306,   72,
      304,  293,   72,  291,  303,  302,   72,  292,   93,   93,
       93,   93,  307,  301,  300,  294,  295,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,  305,   93,   93,   93,   93,  320,   93,

       93,   93,   93,  321,   93,   93,   93,   93,  322,   93,
       93,   93,   93,  323,  299,  298,  312,  289,  311,   43,
       43,   43,  106,  106,  106,  108,  288,  108,   72,  287,
      286,   72,   72,   72,   72,   72,  285,  284,  283,  282,
      281,  280,   72,  279,   72,  278,  277,  276,  266,   72,
      265,  264,   72,  262,   72,   72,  261,   72,   72,  260,
      259,  258,  257,  256,   72,   72,  255,  254,  253,   72,
      252,  251,   72,   72,  250,   72,   72,  249,  248,  247,
      246,  245,  235,  234,  233,  232,  231,  230,  229,  228,
       72,  225,  224,  223,  222,  221,  220,  219,   72,  218,

       72,  217,  216,  215,  214,  213,   72,  212,  211,  210,
       72,  207,  206,  205,  204,  203,  202,  201,  190,  189,
      188,  187,  186,  185,  184,  183,  178,  177,  176,  175,
      174,  169,  168,  167,  166,  165,  164,  163,  162,  157,
      156,  155,  154,  153,  153,  107,  151,  150,  149,  138,
      137,  136,   72,   72,  135,  134,  133,  130,  129,  128,
      127,  126,   72,  125,  124,  123,   72,   72,  122,  119,
      116,  115,  114,  113,   72,  112,  111,  110,  109,  107,
      103,  353,   92,   91,   90,   82,   79,   73,   65,   61,
       60,   59,   58,  353,    3,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353
    } ;

static yyconst flex_int16_t yy_chk[760] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    8,   26,    8,
        9,  355,   13,    8,   13,    8,   24,    8,    8,   22,
        9,   14,   14,   14,   14,   25,   26,   22,   24,   25,
       27,   32,   22,   29,   30,   32,   43,   29,    6,  352,

       30,   54,   34,   27,   35,   29,   34,   36,   35,   54,
       29,   42,   42,   69,   36,  351,   69,   83,   35,   46,
       46,   46,   46,   47,   47,   47,   47,   83,   43,   48,
       48,   48,   48,   49,   49,   49,   49,   50,   50,   50,
       50,   51,   51,   51,   51,   52,   52,   52,   52,   47,
       57,   57,   57,   57,   67,   92,   92,   93,   93,   93,
       93,   67,  350,   50,   94,   94,   94,   94,  116,  349,
       49,   50,  348,  107,   48,  107,  161,  161,   51,  347,
       51,  116,  182,  182,   51,  231,   52,   95,   95,   95,
       95,   96,   96,   96,   96,   97,   97,   97,   97,   98,

       98,   98,   98,  231,  346,  345,   94,   99,   99,   99,
       99,  100,  100,  100,  100,  344,  115,   95,  101,  101,
      101,  101,   96,  102,  102,  102,  102,  115,  115,  343,
      342,  341,  131,  277,  125,   99,   98,  115,  125,  277,
      340,  100,   97,  131,  131,  125,  125,  140,  140,  140,
      140,  101,  339,  131,  338,  337,  336,  102,  141,  141,
      141,  141,  142,  142,  142,  142,  335,  143,  143,  143,
      143,  144,  144,  144,  144,  145,  145,  145,  145,  146,
      146,  146,  146,  147,  147,  147,  147,  334,  315,  333,
      140,  332,  142,  143,  315,  331,  142,  144,  330,  141,

      148,  148,  148,  148,  329,  145,  191,  191,  191,  191,
      191,  328,  327,  147,  192,  192,  192,  192,  326,  325,
      146,  324,  193,  193,  193,  193,  319,  194,  194,  194,
      194,  195,  195,  195,  195,  318,  317,  148,  196,  196,
      196,  196,  197,  197,  197,  197,  316,  198,  198,  198,
      198,  199,  199,  199,  199,  200,  200,  200,  200,  314,
      313,  304,  192,  193,  194,  237,  237,  237,  237,  303,
      302,  301,  195,  198,  238,  238,  238,  238,  238,  196,
      239,  239,  239,  239,  240,  240,  240,  240,  241,  241,
      241,  241,  199,  242,  242,  242,  242,  300,  200,  243,

      243,  243,  243,  243,  299,  244,  244,  244,  244,  244,
      268,  268,  268,  268,  239,  298,  240,  297,  296,  289,
      241,  269,  269,  269,  269,  270,  270,  270,  270,  288,
      242,  244,  271,  271,  271,  271,  242,  272,  272,  272,
      272,  275,  275,  275,  275,  290,  290,  290,  290,  293,
      293,  293,  293,  268,  291,  291,  291,  291,  291,  287,
      286,  271,  285,  269,  284,  283,  282,  270,  292,  292,
      292,  292,  292,  281,  280,  272,  275,  294,  294,  294,
      294,  295,  295,  295,  295,  305,  305,  305,  305,  312,
      312,  312,  312,  290,  308,  308,  308,  308,  308,  309,

      309,  309,  309,  309,  310,  310,  310,  310,  310,  311,
      311,  311,  311,  311,  279,  278,  295,  266,  294,  354,
      354,  354,  356,  356,  356,  357,  265,  357,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  235,  234,
      233,  232,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  190,  189,  188,  187,  186,  185,  184,  183,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,

      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      160,  159,  158,  157,  156,  155,  154,  149,  139,  138,
      137,  136,  135,  134,  133,  132,  130,  129,  128,  127,
      126,  124,  123,  122,  121,  120,  119,  118,  117,  114,
      113,  112,  111,  110,  109,  106,  105,  104,  103,   91,
       90,   89,   88,   87,   86,   85,   84,   82,   81,   80,
       79,   78,   77,   76,   75,   74,   73,   71,   70,   68,
       66,   65,   64,   63,   62,   61,   60,   59,   58,   55,
       53,   45,   39,   38,   37,   33,   31,   28,   23,   19,
       18,   17,   16,    3,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int inferencerule_parser_flex_debug;
int inferencerule_parser_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *inferencerule_parsertext;
#line 1 "inferencerule_parser.l"
#line 2 "inferencerule_parser.l"
#include "inferencerule_parser.tab.h"
#include <stdlib.h>
#include <string>
#include <iostream>
#include <stdio.h>
using namespace std;
#line 769 "inferencerule_parser.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int inferencerule_parserlex_destroy (void );

int inferencerule_parserget_debug (void );

void inferencerule_parserset_debug (int debug_flag  );

YY_EXTRA_TYPE inferencerule_parserget_extra (void );

void inferencerule_parserset_extra (YY_EXTRA_TYPE user_defined  );

FILE *inferencerule_parserget_in (void );

void inferencerule_parserset_in  (FILE * in_str  );

FILE *inferencerule_parserget_out (void );

void inferencerule_parserset_out  (FILE * out_str  );

int inferencerule_parserget_leng (void );

char *inferencerule_parserget_text (void );

int inferencerule_parserget_lineno (void );

void inferencerule_parserset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int inferencerule_parserwrap (void );
#else
extern int inferencerule_parserwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( inferencerule_parsertext, inferencerule_parserleng, 1, inferencerule_parserout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( inferencerule_parserin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( inferencerule_parserin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, inferencerule_parserin))==0 && ferror(inferencerule_parserin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(inferencerule_parserin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int inferencerule_parserlex (void);

#define YY_DECL int inferencerule_parserlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after inferencerule_parsertext and inferencerule_parserleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 18 "inferencerule_parser.l"

#line 958 "inferencerule_parser.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! inferencerule_parserin )
			inferencerule_parserin = stdin;

		if ( ! inferencerule_parserout )
			inferencerule_parserout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			inferencerule_parserensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				inferencerule_parser_create_buffer(inferencerule_parserin,YY_BUF_SIZE );
		}

		inferencerule_parser_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of inferencerule_parsertext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 354 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 695 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 19 "inferencerule_parser.l"
{/*cout<<"Comments in Lex\n";*/
                                                return t_Comments;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "inferencerule_parser.l"
{/*cout<<"Operator string\n"; */
                   return t_OperatorString; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "inferencerule_parser.l"
{/* cout<<"Operator:"<<inferencerule_parsertext<<"\n";*/
                               inferencerule_parserlval.string_value=strdup(inferencerule_parsertext);
                               inferencerule_parserlval.string_value[inferencerule_parserleng]='\0'; 
                               /*cout<<"Operator:"<<inferencerule_parsertext;*/
                               return t_String;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "inferencerule_parser.l"
{/*cout<<"Minargs\n"; */
                  return t_MinArgs;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "inferencerule_parser.l"
{/*cout<<"Maxargs\n"; */
                  return t_MaxArgs;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "inferencerule_parser.l"
{ return t_OSquareBrack;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "inferencerule_parser.l"
{ return t_CSquareBrack;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "inferencerule_parser.l"
{ /*cout<<inferencerule_parsertext<<endl;*/
                    inferencerule_parserlval.int_value=atoi(inferencerule_parsertext); return INT_NUMBER; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 40 "inferencerule_parser.l"
{/* Spaces nothing to do */}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "inferencerule_parser.l"
{ /*cout<<"operand1"<<endl;*/
                    return t_Operand1; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "inferencerule_parser.l"
{ /*cout<<"operand2"<<endl;*/
                    return t_Operand2; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "inferencerule_parser.l"
{ /*cout<<"operand3"<<endl;*/
                    return t_Operand3; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "inferencerule_parser.l"
{ /*cout<<"OtherOperands"<<endl;*/
                    return t_OtherOperandsString;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "inferencerule_parser.l"
{ /*cout<<"Infinity"<<endl;*/
                    return t_InfinityString;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "inferencerule_parser.l"
{ /*cout<<"InferringType"<<endl; */
                    return t_InferString;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "inferencerule_parser.l"
{ return t_CastString; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "inferencerule_parser.l"
{ /* cout<<"Type recieved\n"<<inferencerule_parsertext<<endl; */
                  inferencerule_parserlval.string_value=strdup(inferencerule_parsertext);
                   inferencerule_parserlval.string_value[inferencerule_parserleng]='\0'; 
                     /*                   cout<<"Type:"<<inferencerule_parsertext;*/
                   return t_TypeValue; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "inferencerule_parser.l"
{ /*cout<<"MaxComp"<<endl;*/
                 return t_Max;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "inferencerule_parser.l"
{ /*cout<<"MinComp"<<endl;*/
                 return t_Min;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "inferencerule_parser.l"
{ /*cout<<"AddComp"<<endl;*/
                 return t_Add;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "inferencerule_parser.l"
{ /*cout<<"Addall Comp"<<endl;*/
                 return t_Addall;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "inferencerule_parser.l"
{ return t_Hash; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "inferencerule_parser.l"
{ return t_Comma;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "inferencerule_parser.l"
{ return t_OBrack; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "inferencerule_parser.l"
{ return t_CBrack; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "inferencerule_parser.l"
{ return t_SemiColon; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "inferencerule_parser.l"
{ return t_print; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "inferencerule_parser.l"
{ return t_printAll; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "inferencerule_parser.l"
{ return t_Once; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "inferencerule_parser.l"
{ return t_Every; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "inferencerule_parser.l"
{ return t_FOBrack; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "inferencerule_parser.l"
{ return t_FCBrack; }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 87 "inferencerule_parser.l"
{inferencerule_parserlval.string_value=strdup(inferencerule_parsertext);
                   inferencerule_parserlval.string_value[inferencerule_parserleng]='\0'; 
                   /*cout<<"\nString:"<<inferencerule_parsertext;*/
                   return t_StringLiteral; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "inferencerule_parser.l"
{inferencerule_parserlval.string_value=strdup(inferencerule_parsertext);
                   inferencerule_parserlval.string_value[inferencerule_parserleng]='\0'; 
                  /* cout<<"\nKeyword:"<<inferencerule_parsertext;*/
                   return t_KeyWordsOfPrint;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "inferencerule_parser.l"
ECHO;
	YY_BREAK
#line 1248 "inferencerule_parser.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed inferencerule_parserin at a new source and called
			 * inferencerule_parserlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = inferencerule_parserin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( inferencerule_parserwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * inferencerule_parsertext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of inferencerule_parserlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					inferencerule_parserrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			inferencerule_parserrestart(inferencerule_parserin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) inferencerule_parserrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 354 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 354 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 353);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up inferencerule_parsertext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					inferencerule_parserrestart(inferencerule_parserin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( inferencerule_parserwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve inferencerule_parsertext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void inferencerule_parserrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        inferencerule_parserensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            inferencerule_parser_create_buffer(inferencerule_parserin,YY_BUF_SIZE );
	}

	inferencerule_parser_init_buffer(YY_CURRENT_BUFFER,input_file );
	inferencerule_parser_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void inferencerule_parser_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		inferencerule_parserpop_buffer_state();
	 *		inferencerule_parserpush_buffer_state(new_buffer);
     */
	inferencerule_parserensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	inferencerule_parser_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (inferencerule_parserwrap()) processing, but the only time this flag
	 * is looked at is after inferencerule_parserwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void inferencerule_parser_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	inferencerule_parserin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE inferencerule_parser_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) inferencerule_parseralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in inferencerule_parser_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) inferencerule_parseralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in inferencerule_parser_create_buffer()" );

	b->yy_is_our_buffer = 1;

	inferencerule_parser_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with inferencerule_parser_create_buffer()
 * 
 */
    void inferencerule_parser_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		inferencerule_parserfree((void *) b->yy_ch_buf  );

	inferencerule_parserfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a inferencerule_parserrestart() or at EOF.
 */
    static void inferencerule_parser_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	inferencerule_parser_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then inferencerule_parser_init_buffer was _probably_
     * called from inferencerule_parserrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void inferencerule_parser_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		inferencerule_parser_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void inferencerule_parserpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	inferencerule_parserensure_buffer_stack();

	/* This block is copied from inferencerule_parser_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from inferencerule_parser_switch_to_buffer. */
	inferencerule_parser_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void inferencerule_parserpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	inferencerule_parser_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		inferencerule_parser_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void inferencerule_parserensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)inferencerule_parseralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in inferencerule_parserensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)inferencerule_parserrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in inferencerule_parserensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE inferencerule_parser_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) inferencerule_parseralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in inferencerule_parser_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	inferencerule_parser_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to inferencerule_parserlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       inferencerule_parser_scan_bytes() instead.
 */
YY_BUFFER_STATE inferencerule_parser_scan_string (yyconst char * yystr )
{
    
	return inferencerule_parser_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to inferencerule_parserlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE inferencerule_parser_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) inferencerule_parseralloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in inferencerule_parser_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = inferencerule_parser_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in inferencerule_parser_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up inferencerule_parsertext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		inferencerule_parsertext[inferencerule_parserleng] = (yy_hold_char); \
		(yy_c_buf_p) = inferencerule_parsertext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		inferencerule_parserleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int inferencerule_parserget_lineno  (void)
{
        
    return inferencerule_parserlineno;
}

/** Get the input stream.
 * 
 */
FILE *inferencerule_parserget_in  (void)
{
        return inferencerule_parserin;
}

/** Get the output stream.
 * 
 */
FILE *inferencerule_parserget_out  (void)
{
        return inferencerule_parserout;
}

/** Get the length of the current token.
 * 
 */
int inferencerule_parserget_leng  (void)
{
        return inferencerule_parserleng;
}

/** Get the current token.
 * 
 */

char *inferencerule_parserget_text  (void)
{
        return inferencerule_parsertext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void inferencerule_parserset_lineno (int  line_number )
{
    
    inferencerule_parserlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see inferencerule_parser_switch_to_buffer
 */
void inferencerule_parserset_in (FILE *  in_str )
{
        inferencerule_parserin = in_str ;
}

void inferencerule_parserset_out (FILE *  out_str )
{
        inferencerule_parserout = out_str ;
}

int inferencerule_parserget_debug  (void)
{
        return inferencerule_parser_flex_debug;
}

void inferencerule_parserset_debug (int  bdebug )
{
        inferencerule_parser_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from inferencerule_parserlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    inferencerule_parserin = stdin;
    inferencerule_parserout = stdout;
#else
    inferencerule_parserin = (FILE *) 0;
    inferencerule_parserout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * inferencerule_parserlex_init()
     */
    return 0;
}

/* inferencerule_parserlex_destroy is for both reentrant and non-reentrant scanners. */
int inferencerule_parserlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		inferencerule_parser_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		inferencerule_parserpop_buffer_state();
	}

	/* Destroy the stack itself. */
	inferencerule_parserfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * inferencerule_parserlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *inferencerule_parseralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *inferencerule_parserrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void inferencerule_parserfree (void * ptr )
{
	free( (char *) ptr );	/* see inferencerule_parserrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 101 "inferencerule_parser.l"



int inferencerule_parserwrap(void) {
 return 1;
}
/*
int main()
{
inferencerule_parserlex();
return 0;
}
*/

